name: "Tools - Validate Dockerfile Schema"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  validate-dockerfile-schema:
    name: Haskell Linter
    runs-on: ubuntu-latest

#    strategy:
#      max-parallel: 1
#      fail-fast: true
#      matrix:
 #       files: ["Dockerfile", "docker/Dockerfile"]
        
    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          #dockerfile: ${{ matrix.files }}
          failure-threshold: error
          recursive: true
