---
name: "Tools - Validate YAML Schema"

"on":
  pull_request:
    branches:
      - "master"
    paths:
      - ".yamllint"
      - "**.yaml"
      - "**.yml"
      - "**.yml.example"

permissions:
  contents: read

jobs:
  validate-yaml:
    name: YAML Linter
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Validate YAML files
        run: yamllint .

      # - name: malicious step
        # run: echo "pwned" && cat /etc/passwd

